name: Periodic Check
on:
  schedule:
    - cron: "31 1,12 * * *"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout onecontext
        uses: actions/checkout@v2
        with:
          path: onecontext
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: Move onecontext source code to V Modules
        run: mv ./onecontext ~/.vmodules
      - name: Execute Tests
        run: ~/.vmodules/onecontext/bin/test
